### ISSUE TITLE
seems to be obviously mistake

### ISSUE THREAD

**Issue by tomasen** [jbenet/go-reuseport#10]
on impl_unix.go  line:109
`if lfamily != rfamily && lprotocol != rfamily {`

seems should be 
`if lfamily != rfamily && lprotocol != rprotocol {`

**Comment by jbenet** [comment]
@tomasen you're right! i believe it should also be:

```go
if lfamily != rfamily || lprotocol != rprotocol {
```

fixing in: #11

---

@whyrusleeping have we seen any of this in go-ipfs?
