### ISSUE TITLE
no need for multiple epoll fds

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-reuseport#8]
epoll_ctl_add is safe to call in a different thread, even while another thread (goroutine) is in epoll_wait. Knowing this, we can have a single 'poller' instance that communicates with a master loop. I can work on this if you'd like, although you might be more familiar with the code, let me know.

ref: http://man7.org/linux/man-pages/man2/epoll_wait.2.html#NOTES

**Comment by jbenet** [comment]
From that man page I'm not sure epoll can add arbitrary numbers of fds to one epoll fd. Maybe test it with 100k?



—

**Comment by whyrusleeping** [comment]
better refs: http://man7.org/linux/man-pages/man7/epoll.7.html (under /proc interfaces)

and here: https://banu.com/blog/2/how-to-use-epoll-a-complete-example-in-c/ discusses the differences between select and epoll.

**Comment by jbenet** [comment]
ok

**Comment by Kubuxu** [comment]
Resolved in #17
